definitions:
  weatherData.Astro:
    properties:
      moon_illumination:
        type: string
      moon_phase:
        type: string
      moonrise:
        type: string
      moonset:
        type: string
      sunrise:
        type: string
      sunset:
        type: string
    type: object
  weatherData.Condition:
    properties:
      code:
        type: integer
      icon:
        type: string
      text:
        type: string
    type: object
  weatherData.Current:
    properties:
      cloud:
        type: integer
      condition:
        properties:
          code:
            type: integer
          icon:
            type: string
          text:
            type: string
        type: object
      feelslike_c:
        type: number
      feelslike_f:
        type: number
      gust_kph:
        type: number
      gust_mph:
        type: number
      humidity:
        type: integer
      is_day:
        type: integer
      last_updated:
        type: string
      last_updated_epoch:
        type: integer
      precip_in:
        type: number
      precip_mm:
        type: number
      pressure_in:
        type: number
      pressure_mb:
        type: number
      temp_c:
        type: number
      temp_f:
        type: number
      uv:
        type: number
      vis_km:
        type: number
      vis_miles:
        type: number
      wind_degree:
        type: integer
      wind_dir:
        type: string
      wind_kph:
        type: number
      wind_mph:
        type: number
    type: object
  weatherData.Day:
    properties:
      avghumidity:
        type: number
      avgtemp_c:
        type: number
      avgtemp_f:
        type: number
      avgvis_km:
        type: number
      avgvis_miles:
        type: number
      condition:
        $ref: '#/definitions/weatherData.Condition'
      maxtemp_c:
        type: number
      maxtemp_f:
        type: number
      maxwind_kph:
        type: number
      maxwind_mph:
        type: number
      mintemp_c:
        type: number
      mintemp_f:
        type: number
      totalprecip_in:
        type: number
      totalprecip_mm:
        type: number
      uv:
        type: number
    type: object
  weatherData.ForeCastData:
    properties:
      current:
        $ref: '#/definitions/weatherData.Current'
      forecast:
        $ref: '#/definitions/weatherData.Forecast'
      location:
        $ref: '#/definitions/weatherData.Location'
    type: object
  weatherData.Forecast:
    properties:
      forecastday:
        items:
          $ref: '#/definitions/weatherData.Forecastday'
        type: array
    type: object
  weatherData.Forecastday:
    properties:
      astro:
        $ref: '#/definitions/weatherData.Astro'
      date:
        type: string
      date_epoch:
        type: integer
      day:
        $ref: '#/definitions/weatherData.Day'
      hour:
        items:
          $ref: '#/definitions/weatherData.Hour'
        type: array
    type: object
  weatherData.FutureData:
    properties:
      forecast:
        $ref: '#/definitions/weatherData.Forecast'
      location:
        $ref: '#/definitions/weatherData.Location'
    type: object
  weatherData.Hour:
    properties:
      chance_of_rain:
        type: integer
      chance_of_snow:
        type: integer
      cloud:
        type: integer
      condition:
        $ref: '#/definitions/weatherData.Condition'
      dewpoint_c:
        type: number
      dewpoint_f:
        type: number
      feelslike_c:
        type: number
      feelslike_f:
        type: number
      gust_kph:
        type: number
      gust_mph:
        type: number
      heatindex_c:
        type: number
      heatindex_f:
        type: number
      humidity:
        type: integer
      is_day:
        type: integer
      precip_in:
        type: number
      precip_mm:
        type: number
      pressure_in:
        type: number
      pressure_mb:
        type: number
      temp_c:
        type: number
      temp_f:
        type: number
      time:
        type: string
      time_epoch:
        type: integer
      vis_km:
        type: number
      vis_miles:
        type: number
      will_it_rain:
        type: integer
      will_it_snow:
        type: integer
      wind_degree:
        type: integer
      wind_dir:
        type: string
      wind_kph:
        type: number
      wind_mph:
        type: number
      windchill_c:
        type: number
      windchill_f:
        type: number
    type: object
  weatherData.Location:
    properties:
      country:
        type: string
      lat:
        type: number
      localtime:
        type: string
      localtime_epoch:
        type: integer
      lon:
        type: number
      name:
        type: string
      region:
        type: string
      tz_id:
        type: string
    type: object
  weatherData.RealTimeData:
    properties:
      current:
        properties:
          cloud:
            type: integer
          condition:
            properties:
              code:
                type: integer
              icon:
                type: string
              text:
                type: string
            type: object
          feelslike_c:
            type: number
          feelslike_f:
            type: number
          gust_kph:
            type: number
          gust_mph:
            type: number
          humidity:
            type: integer
          is_day:
            type: integer
          last_updated:
            type: string
          last_updated_epoch:
            type: integer
          precip_in:
            type: number
          precip_mm:
            type: number
          pressure_in:
            type: number
          pressure_mb:
            type: number
          temp_c:
            type: number
          temp_f:
            type: number
          uv:
            type: number
          vis_km:
            type: number
          vis_miles:
            type: number
          wind_degree:
            type: integer
          wind_dir:
            type: string
          wind_kph:
            type: number
          wind_mph:
            type: number
        type: object
      location:
        properties:
          country:
            type: string
          lat:
            type: number
          localtime:
            type: string
          localtime_epoch:
            type: integer
          lon:
            type: number
          name:
            type: string
          region:
            type: string
          tz_id:
            type: string
        type: object
    type: object
  weatherData.TimeZoneData:
    properties:
      location:
        $ref: '#/definitions/weatherData.Location'
    type: object
info:
  contact: {}
paths:
  /weather/forecast:
    get:
      consumes:
      - application/json
      description: Retrieve weather forecast data based on the provided query and
        number of days.
      parameters:
      - description: Location query
        in: query
        name: q
        required: true
        type: string
      - description: Number of days for the forecast
        in: query
        name: days
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/weatherData.ForeCastData'
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal server error
      summary: Get weather forecast data
      tags:
      - Weather
  /weather/future:
    get:
      consumes:
      - application/json
      description: Retrieve future weather data based on the provided query and date.
      parameters:
      - description: Location query
        in: query
        name: q
        required: true
        type: string
      - description: Date for the forecast (YYYY-MM-DD format)
        in: query
        name: dt
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/weatherData.FutureData'
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal server error
      summary: Get future weather data
      tags:
      - Weather
  /weather/real-time:
    get:
      consumes:
      - application/json
      description: Retrieve real-time weather data based on the provided query.
      parameters:
      - description: Location query
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/weatherData.RealTimeData'
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal server error
      summary: Get real-time weather data
      tags:
      - Weather
  /weather/time-zone:
    get:
      consumes:
      - application/json
      description: Retrieve time zone data based on the provided location query.
      parameters:
      - description: Location query
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/weatherData.TimeZoneData'
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: Not found
        "500":
          description: Internal server error
      summary: Get time zone data
      tags:
      - Weather
swagger: "2.0"
